# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Metecol
tagline:          'Research and Development Company'
description:      'We produce medical equipment'
url:              http://metecol.com

author:
  name:           'Mark Vital'
  url:            https://twitter.com/markvitals

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/metecol
